package com.xkumo.xstock.datacollector.client.core.service;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://service.datacollector.xstock.xkumo.com/")
public class Exception_Exception extends java.lang.Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private com.xkumo.xstock.datacollector.client.core.service.Exception faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public Exception_Exception(
			String message,
			com.xkumo.xstock.datacollector.client.core.service.Exception faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public Exception_Exception(
			String message,
			com.xkumo.xstock.datacollector.client.core.service.Exception faultInfo,
			Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         com.xkumo.xstock.datacollector.client.core.service.Exception
	 */
	public com.xkumo.xstock.datacollector.client.core.service.Exception getFaultInfo() {
		return faultInfo;
	}

}
