package com.xkumo.xstock.datacollector.client.core.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "StockServiceDelegate", targetNamespace = "http://service.datacollector.xstock.xkumo.com/")
public interface StockServiceDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns
	 *         com.xkumo.xstock.datacollector.client.core.service.SinaDailyStockData
	 * @throws Exception_Exception
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getData", targetNamespace = "http://service.datacollector.xstock.xkumo.com/", className = "com.xkumo.xstock.datacollector.client.core.service.GetData")
	@ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://service.datacollector.xstock.xkumo.com/", className = "com.xkumo.xstock.datacollector.client.core.service.GetDataResponse")
	public SinaDailyStockData getData(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1)
			throws Exception_Exception;

}
