package com.xkumo.xstock.datacollector.client.core.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * StockServiceService service = new StockServiceService();
 * StockServiceDelegate portType = service.getStockServicePort();
 * portType.getData(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "StockServiceService", targetNamespace = "http://service.datacollector.xstock.xkumo.com/", wsdlLocation = "file:/E:/KeyData/\u6295\u8d44\u7406\u8d22/software/com.xkumo.xstock.datacollector/WebRoot/WEB-INF/wsdl/StockServiceService.wsdl")
public class StockServiceService extends Service {

	private final static URL STOCKSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.xkumo.xstock.datacollector.client.core.service.StockServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.xkumo.xstock.datacollector.client.core.service.StockServiceService.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"file:/E:/KeyData/\u6295\u8d44\u7406\u8d22/software/com.xkumo.xstock.datacollector/WebRoot/WEB-INF/wsdl/StockServiceService.wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'file:/E:/KeyData/\u6295\u8d44\u7406\u8d22/software/com.xkumo.xstock.datacollector/WebRoot/WEB-INF/wsdl/StockServiceService.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		STOCKSERVICESERVICE_WSDL_LOCATION = url;
	}

	public StockServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public StockServiceService() {
		super(STOCKSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://service.datacollector.xstock.xkumo.com/",
				"StockServiceService"));
	}

	/**
	 * 
	 * @return returns StockServiceDelegate
	 */
	@WebEndpoint(name = "StockServicePort")
	public StockServiceDelegate getStockServicePort() {
		return super.getPort(new QName(
				"http://service.datacollector.xstock.xkumo.com/",
				"StockServicePort"), StockServiceDelegate.class);
	}

}
