package com.xkumo.xstock.weixin.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WebServiceDelegate", targetNamespace = "http://webservice.xstock.xkumo.com/")
public interface WebServiceDelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "startTask", targetNamespace = "http://webservice.xstock.xkumo.com/", className = "com.xkumo.xstock.weixin.webservice.client.StartTask")
	@ResponseWrapper(localName = "startTaskResponse", targetNamespace = "http://webservice.xstock.xkumo.com/", className = "com.xkumo.xstock.weixin.webservice.client.StartTaskResponse")
	public void startTask(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "stopTask", targetNamespace = "http://webservice.xstock.xkumo.com/", className = "com.xkumo.xstock.weixin.webservice.client.StopTask")
	@ResponseWrapper(localName = "stopTaskResponse", targetNamespace = "http://webservice.xstock.xkumo.com/", className = "com.xkumo.xstock.weixin.webservice.client.StopTaskResponse")
	public void stopTask(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
