package com.xkumo.xstock.weixin.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WebServiceService", targetNamespace = "http://webservice.xstock.xkumo.com/", wsdlLocation = "http://www.xkumo.com:8080/XStockSystem/WebServicePort?wsdl")
public class WebServiceService extends Service {

	private final static URL WEBSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.xkumo.xstock.weixin.webservice.client.WebServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.xkumo.xstock.weixin.webservice.client.WebServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://www.xkumo.com:8080/XStockSystem/WebServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://www.xkumo.com:8080/XStockSystem/WebServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WEBSERVICESERVICE_WSDL_LOCATION = url;
	}

	public WebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WebServiceService() {
		super(WEBSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://webservice.xstock.xkumo.com/", "WebServiceService"));
	}

	/**
	 * 
	 * @return returns WebServiceDelegate
	 */
	@WebEndpoint(name = "WebServicePort")
	public WebServiceDelegate getWebServicePort() {
		return super.getPort(new QName("http://webservice.xstock.xkumo.com/",
				"WebServicePort"), WebServiceDelegate.class);
	}

}
