//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XStockDataCollectorTest.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.datacollector.xstock.xkumo.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.datacollector.xstock.xkumo.com/")]
    public partial class sinaDailyStockData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bottompriceField;
        
        private string buy1numberField;
        
        private string buy1priceField;
        
        private string buy2numberField;
        
        private string buy2priceField;
        
        private string buy3numberField;
        
        private string buy3priceField;
        
        private string buy4numberField;
        
        private string buy4priceField;
        
        private string buy5numberField;
        
        private string buy5priceField;
        
        private string buypriceField;
        
        private string contentField;
        
        private string currentpriceField;
        
        private System.DateTime datadayField;
        
        private bool datadayFieldSpecified;
        
        private string datatimeField;
        
        private string lastclosepriceField;
        
        private float ma10Field;
        
        private float ma120Field;
        
        private float ma20Field;
        
        private float ma240Field;
        
        private float ma30Field;
        
        private float ma5Field;
        
        private float ma60Field;
        
        private string openpriceField;
        
        private string sell1numberField;
        
        private string sell1priceField;
        
        private string sell2numberField;
        
        private string sell2priceField;
        
        private string sell3numberField;
        
        private string sell3priceField;
        
        private string sell4numberField;
        
        private string sell4priceField;
        
        private string sell5numberField;
        
        private string sell5priceField;
        
        private string sellpriceField;
        
        private string stockcodeField;
        
        private string stockexchangecodeField;
        
        private string stocknameField;
        
        private string toppriceField;
        
        private string transactionamountField;
        
        private string transactionnumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bottomprice {
            get {
                return this.bottompriceField;
            }
            set {
                this.bottompriceField = value;
                this.RaisePropertyChanged("bottomprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string buy1number {
            get {
                return this.buy1numberField;
            }
            set {
                this.buy1numberField = value;
                this.RaisePropertyChanged("buy1number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string buy1price {
            get {
                return this.buy1priceField;
            }
            set {
                this.buy1priceField = value;
                this.RaisePropertyChanged("buy1price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string buy2number {
            get {
                return this.buy2numberField;
            }
            set {
                this.buy2numberField = value;
                this.RaisePropertyChanged("buy2number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string buy2price {
            get {
                return this.buy2priceField;
            }
            set {
                this.buy2priceField = value;
                this.RaisePropertyChanged("buy2price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string buy3number {
            get {
                return this.buy3numberField;
            }
            set {
                this.buy3numberField = value;
                this.RaisePropertyChanged("buy3number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string buy3price {
            get {
                return this.buy3priceField;
            }
            set {
                this.buy3priceField = value;
                this.RaisePropertyChanged("buy3price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string buy4number {
            get {
                return this.buy4numberField;
            }
            set {
                this.buy4numberField = value;
                this.RaisePropertyChanged("buy4number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string buy4price {
            get {
                return this.buy4priceField;
            }
            set {
                this.buy4priceField = value;
                this.RaisePropertyChanged("buy4price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string buy5number {
            get {
                return this.buy5numberField;
            }
            set {
                this.buy5numberField = value;
                this.RaisePropertyChanged("buy5number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string buy5price {
            get {
                return this.buy5priceField;
            }
            set {
                this.buy5priceField = value;
                this.RaisePropertyChanged("buy5price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string buyprice {
            get {
                return this.buypriceField;
            }
            set {
                this.buypriceField = value;
                this.RaisePropertyChanged("buyprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string currentprice {
            get {
                return this.currentpriceField;
            }
            set {
                this.currentpriceField = value;
                this.RaisePropertyChanged("currentprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime dataday {
            get {
                return this.datadayField;
            }
            set {
                this.datadayField = value;
                this.RaisePropertyChanged("dataday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datadaySpecified {
            get {
                return this.datadayFieldSpecified;
            }
            set {
                this.datadayFieldSpecified = value;
                this.RaisePropertyChanged("datadaySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string datatime {
            get {
                return this.datatimeField;
            }
            set {
                this.datatimeField = value;
                this.RaisePropertyChanged("datatime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string lastcloseprice {
            get {
                return this.lastclosepriceField;
            }
            set {
                this.lastclosepriceField = value;
                this.RaisePropertyChanged("lastcloseprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public float ma10 {
            get {
                return this.ma10Field;
            }
            set {
                this.ma10Field = value;
                this.RaisePropertyChanged("ma10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public float ma120 {
            get {
                return this.ma120Field;
            }
            set {
                this.ma120Field = value;
                this.RaisePropertyChanged("ma120");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public float ma20 {
            get {
                return this.ma20Field;
            }
            set {
                this.ma20Field = value;
                this.RaisePropertyChanged("ma20");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public float ma240 {
            get {
                return this.ma240Field;
            }
            set {
                this.ma240Field = value;
                this.RaisePropertyChanged("ma240");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public float ma30 {
            get {
                return this.ma30Field;
            }
            set {
                this.ma30Field = value;
                this.RaisePropertyChanged("ma30");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public float ma5 {
            get {
                return this.ma5Field;
            }
            set {
                this.ma5Field = value;
                this.RaisePropertyChanged("ma5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public float ma60 {
            get {
                return this.ma60Field;
            }
            set {
                this.ma60Field = value;
                this.RaisePropertyChanged("ma60");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string openprice {
            get {
                return this.openpriceField;
            }
            set {
                this.openpriceField = value;
                this.RaisePropertyChanged("openprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string sell1number {
            get {
                return this.sell1numberField;
            }
            set {
                this.sell1numberField = value;
                this.RaisePropertyChanged("sell1number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string sell1price {
            get {
                return this.sell1priceField;
            }
            set {
                this.sell1priceField = value;
                this.RaisePropertyChanged("sell1price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string sell2number {
            get {
                return this.sell2numberField;
            }
            set {
                this.sell2numberField = value;
                this.RaisePropertyChanged("sell2number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string sell2price {
            get {
                return this.sell2priceField;
            }
            set {
                this.sell2priceField = value;
                this.RaisePropertyChanged("sell2price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string sell3number {
            get {
                return this.sell3numberField;
            }
            set {
                this.sell3numberField = value;
                this.RaisePropertyChanged("sell3number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string sell3price {
            get {
                return this.sell3priceField;
            }
            set {
                this.sell3priceField = value;
                this.RaisePropertyChanged("sell3price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string sell4number {
            get {
                return this.sell4numberField;
            }
            set {
                this.sell4numberField = value;
                this.RaisePropertyChanged("sell4number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string sell4price {
            get {
                return this.sell4priceField;
            }
            set {
                this.sell4priceField = value;
                this.RaisePropertyChanged("sell4price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string sell5number {
            get {
                return this.sell5numberField;
            }
            set {
                this.sell5numberField = value;
                this.RaisePropertyChanged("sell5number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string sell5price {
            get {
                return this.sell5priceField;
            }
            set {
                this.sell5priceField = value;
                this.RaisePropertyChanged("sell5price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string sellprice {
            get {
                return this.sellpriceField;
            }
            set {
                this.sellpriceField = value;
                this.RaisePropertyChanged("sellprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string stockcode {
            get {
                return this.stockcodeField;
            }
            set {
                this.stockcodeField = value;
                this.RaisePropertyChanged("stockcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string stockexchangecode {
            get {
                return this.stockexchangecodeField;
            }
            set {
                this.stockexchangecodeField = value;
                this.RaisePropertyChanged("stockexchangecode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string stockname {
            get {
                return this.stocknameField;
            }
            set {
                this.stocknameField = value;
                this.RaisePropertyChanged("stockname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string topprice {
            get {
                return this.toppriceField;
            }
            set {
                this.toppriceField = value;
                this.RaisePropertyChanged("topprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string transactionamount {
            get {
                return this.transactionamountField;
            }
            set {
                this.transactionamountField = value;
                this.RaisePropertyChanged("transactionamount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string transactionnumber {
            get {
                return this.transactionnumberField;
            }
            set {
                this.transactionnumberField = value;
                this.RaisePropertyChanged("transactionnumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.datacollector.xstock.xkumo.com/", ConfigurationName="ServiceReference1.StockServiceDelegate")]
    public interface StockServiceDelegate {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(XStockDataCollectorTest.ServiceReference1.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        XStockDataCollectorTest.ServiceReference1.getDataResponse getData(XStockDataCollectorTest.ServiceReference1.getDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getData", WrapperNamespace="http://service.datacollector.xstock.xkumo.com/", IsWrapped=true)]
    public partial class getDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.datacollector.xstock.xkumo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.datacollector.xstock.xkumo.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getDataRequest() {
        }
        
        public getDataRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataResponse", WrapperNamespace="http://service.datacollector.xstock.xkumo.com/", IsWrapped=true)]
    public partial class getDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.datacollector.xstock.xkumo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XStockDataCollectorTest.ServiceReference1.sinaDailyStockData @return;
        
        public getDataResponse() {
        }
        
        public getDataResponse(XStockDataCollectorTest.ServiceReference1.sinaDailyStockData @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockServiceDelegateChannel : XStockDataCollectorTest.ServiceReference1.StockServiceDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockServiceDelegateClient : System.ServiceModel.ClientBase<XStockDataCollectorTest.ServiceReference1.StockServiceDelegate>, XStockDataCollectorTest.ServiceReference1.StockServiceDelegate {
        
        public StockServiceDelegateClient() {
        }
        
        public StockServiceDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockServiceDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XStockDataCollectorTest.ServiceReference1.getDataResponse XStockDataCollectorTest.ServiceReference1.StockServiceDelegate.getData(XStockDataCollectorTest.ServiceReference1.getDataRequest request) {
            return base.Channel.getData(request);
        }
        
        public XStockDataCollectorTest.ServiceReference1.sinaDailyStockData getData(string arg0, string arg1) {
            XStockDataCollectorTest.ServiceReference1.getDataRequest inValue = new XStockDataCollectorTest.ServiceReference1.getDataRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            XStockDataCollectorTest.ServiceReference1.getDataResponse retVal = ((XStockDataCollectorTest.ServiceReference1.StockServiceDelegate)(this)).getData(inValue);
            return retVal.@return;
        }
    }
}
